# Setup
title:               Pidroh
tagline:             'making games'
description:         'Currently developing Brave Ball which <a href="https://store.steampowered.com/app/1638970/Brave_Ball/" target="_blank">you can wishlist on Steam</a>.'
baseurl:             '/site'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Pedro Gabriel Fonteles Furtado
  url:               https://store.steampowered.com/search/?developer=Pidroh
  email:             gabrielpff2@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
